### ISSUE TITLE
Startup issue and probably wrong interface

### ISSUE THREAD

**Issue by maxdd** [MikeHorn-git/docker-snort3#1]
Hello,
with your built image i get

```
--------------------------------------------------
o")~   Snort++ 3.1.82.0
--------------------------------------------------
--------------------------------------------------
pcap DAQ configured to passive.

Snort successfully validated the configuration (with 0 warnings).
o")~   Snort exiting
```

i saw that you are using eth0 but in my case the laptop has not such interface.
So i /bin/bash'ed in and tried 

`/snort/bin/snort -T -i wlp3s0`

but got the same error

**Comment by maxdd** [comment]
The way around for me was at least to add

```
user: root
network_mode: host
```

when using your built image

**Comment by MikeHorn-git** [comment]
Hello, thanks for your feedback.

Great idea to add the network interface in the docker-compose.yml, thanks. It's done.

For the startup issue is normal. The -T argument is for testing, that's why you got this output.
I need to add classic feature, like https://github.com/snort3/snort3?tab=readme-ov-file#run-snort
